services:
  mysql:
    image: mysql:8.0
    container_name: finance-mysql-${NODE_ENV}
    env_file:
      - .env
    volumes:
      - finance_mysql_data:/var/lib/mysql
    networks:
      - finance-network
    restart: ${RESTART_POLICY}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: finance-phpmyadmin-${NODE_ENV}
    environment:
      PMA_HOST: mysql
    ports:
      - "127.0.0.1:4760:80"
    depends_on:
      - mysql
    networks:
      - finance-network


  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: finance-nest-${NODE_ENV}
    env_file:
      - .env
    ports:
      - "127.0.0.1:4770:3000"
    depends_on:
      - mysql
    networks:
      - finance-network
    restart: ${RESTART_POLICY}

  vite:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: finance-vite-${NODE_ENV}
    ports:
      - "127.0.0.1:4750:80"
    depends_on:
      - nest
    networks:
      - finance-network
    restart: ${RESTART_POLICY}

volumes:
  finance_mysql_data:

networks:
  finance-network:
    driver: bridge
